# Generated by Django 3.1.2 on 2020-11-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('os', models.TextField()),
                ('processor', models.TextField()),
                ('display', models.TextField()),
                ('resolution', models.TextField()),
                ('built_in_memory', models.TextField()),
                ('ram', models.TextField()),
            ],
        ),
    ]
